/**
 * @file app_config.hpp
 * @brief Application Configuration - All project-specific settings
 *
 * This file contains all project-specific configuration that should NOT
 * be reused in other projects. For reusable components, see library/.
 *
 * @note WiFi credentials and API keys should be stored in NVS for production.
 *       The compile-time defaults here are for development only.
 */

#pragma once

// Generated provisioning config (run 'go run tools/setup/main.go' to generate)
#include <provisioning_config.h>

#include <driver/gpio.h>

#include <cstdint>
#include <string_view>

namespace app::config {

// =============================================================================
// Power Management
// =============================================================================

/// Deep sleep interval in seconds
inline constexpr uint64_t SLEEP_INTERVAL_SEC = 30;

/// BSEC operation mode (generated by setup tool)
inline constexpr bool BSEC_DEEP_SLEEP_MODE = false;

/// Minimum battery voltage (mV) before entering permanent sleep
inline constexpr uint32_t BATTERY_MIN_MV = 2400;

// =============================================================================
// I2C Bus Configuration
// =============================================================================

/// I2C SDA pin (ESP32-C3 Super Mini)
inline constexpr gpio_num_t I2C_SDA_PIN = GPIO_NUM_8;

/// I2C SCL pin (ESP32-C3 Super Mini)
inline constexpr gpio_num_t I2C_SCL_PIN = GPIO_NUM_9;

/// I2C bus speed in Hz
inline constexpr uint32_t I2C_FREQ_HZ = 100'000;

// =============================================================================
// Sensor Configuration
// =============================================================================

/// BME680 I2C address (SDO→GND = 0x76, SDO→VCC = 0x77)
inline constexpr uint8_t BME680_ADDRESS = 0x77;

// =============================================================================
// WiFi Configuration
// =============================================================================
// Credentials are provisioned via BLE (Improv WiFi) and stored in NVS.
// See tools/setup for provisioning configuration.

inline constexpr uint8_t WIFI_MAX_RETRIES = 5;
inline constexpr uint32_t WIFI_TIMEOUT_MS = 15'000;

// =============================================================================
// Cloud Configuration
// =============================================================================
// Base URL is in cloud/endpoints.hpp (auto-generated by
// tools/provision/cmd/genconfig)

namespace cloud {

/// Request timeout
inline constexpr uint32_t REQUEST_TIMEOUT_MS = 30'000;

/// Token expiry buffer - refresh this many seconds before expiry
inline constexpr uint32_t TOKEN_REFRESH_BUFFER_SEC = 300; // 5 minutes

/// Command poll interval in minutes
inline constexpr uint8_t COMMAND_POLL_INTERVAL_MIN = 1;

/// Telemetry send interval in minutes
inline constexpr uint8_t TELEMETRY_INTERVAL_MIN = 5;

/// Skip TLS certificate verification (ONLY for development!)
inline constexpr bool SKIP_CERT_VERIFY = false;

} // namespace cloud

// =============================================================================
// Timing & Intervals
// =============================================================================

inline constexpr uint32_t NETWORK_TIMEOUT_MS = 30'000;

// =============================================================================
// Battery Monitoring (ADC)
// =============================================================================

namespace battery {
inline constexpr gpio_num_t ADC_PIN = GPIO_NUM_2;
inline constexpr float VOLTAGE_DIVIDER_RATIO = 2.0F;
inline constexpr uint32_t ADC_VREF_MV = 1100;
} // namespace battery

} // namespace app::config
