/**
 * @file app_config.hpp
 * @brief Application Configuration - Project-specific settings
 *
 * This file contains all project-specific configuration that should NOT
 * be reused in other projects. For reusable components, see library/.
 *
 * @note WiFi credentials and API keys should be stored in NVS for production.
 *       The compile-time defaults here are for development only.
 */

#pragma once

#include <driver/gpio.h>

#include <cstdint>
#include <string_view>

namespace app::config {

// =============================================================================
// Power Management
// =============================================================================

/// Deep sleep interval in seconds (5 minutes default)
inline constexpr uint64_t SLEEP_INTERVAL_SEC = 30;

// =============================================================================
// I2C Configuration
// =============================================================================

/// I2C SDA pin (adjust for your board)
inline constexpr gpio_num_t I2C_SDA_PIN = GPIO_NUM_8;

/// I2C SCL pin (adjust for your board)
inline constexpr gpio_num_t I2C_SCL_PIN = GPIO_NUM_9;

/// BME680 I2C address (0x76 if SDO→GND, 0x77 if SDO→VCC)
inline constexpr uint8_t BME680_ADDRESS = 0x77;

/// Minimum battery voltage (mV) before entering permanent sleep
inline constexpr uint32_t BATTERY_MIN_MV = 2400; // CR123A ~2.4V is near empty

// =============================================================================
// WiFi Configuration (Development defaults - use NVS in production)
// =============================================================================

inline constexpr std::string_view WIFI_SSID = "YOUR_SSID";
inline constexpr std::string_view WIFI_PASSWORD = "YOUR_PASSWORD";

/// Maximum WiFi connection attempts before giving up and sleeping
inline constexpr uint8_t WIFI_MAX_RETRIES = 5;

/// WiFi connection timeout in milliseconds
inline constexpr uint32_t WIFI_TIMEOUT_MS = 15'000;

// =============================================================================
// GCP Cloud Configuration
// =============================================================================

/// GCP Project ID
inline constexpr std::string_view GCP_PROJECT_ID = "your-gcp-project";

/// Cloud Function / Cloud Run endpoint for telemetry
inline constexpr std::string_view TELEMETRY_ENDPOINT =
    "https://your-region-your-project.cloudfunctions.net/telemetry";

/// Cloud Function / Cloud Run endpoint for commands (polling)
inline constexpr std::string_view COMMANDS_ENDPOINT =
    "https://your-region-your-project.cloudfunctions.net/commands";

/// JWT token lifetime in seconds (GCP max is 3600)
inline constexpr uint32_t JWT_LIFETIME_SEC = 3600;

// =============================================================================
// Device Identity
// =============================================================================

/// Device ID prefix (MAC address will be appended)
inline constexpr std::string_view DEVICE_ID_PREFIX = "probe-";

/// Firmware version
inline constexpr const char *FIRMWARE_VERSION = "0.1.0";

// =============================================================================
// Timing & Intervals
// =============================================================================

/// How often to poll for commands (every N wake cycles)
inline constexpr uint8_t COMMAND_POLL_INTERVAL = 1; // Every wake cycle

/// Maximum time to spend on network operations before aborting (ms)
inline constexpr uint32_t NETWORK_TIMEOUT_MS = 30'000;


// BSEC operation mode (generated by setup tool)
inline constexpr bool BSEC_DEEP_SLEEP_MODE = false;
} // namespace app::config
